test: Add GitPod support
eclipse/che-che4z-lsp-for-cobol pull request #1183
Opened 2021-11-10 12:33 UTC by nalmabrcom

Signed-off-by: Maryna Nalbandian <maryna.nalbandian@broadcom.com>

2021-12-17 12:45 UTC, temanbrcom approved these changes
📟

2021-12-21 09:14 UTC, grianbrcom requested changes

2021-12-21 09:14 UTC, grianbrcom commented on tests/cypress/integration/LSP/lsp.spec.js
> +        cy.log('Seems an error in VSCODE');
Looks like debug logging. Can you delete it?

2021-12-21 09:14 UTC, grianbrcom commented on tests/cypress/integration/LSP/lsp.spec.js
> +      cy.log('Seems an error in VSCODE');
And here too.

2021-12-21 09:14 UTC, grianbrcom commented on tests/cypress/integration/LSP/lsp.spec.js
> +      cy.log('Seems an error');
Again debug logging.

2021-12-21 09:26 UTC, grianbrcom approved these changes
:otter:

2021-12-21 09:52 UTC, merged