refactor: clean the code to remove dependency from analysisResult
eclipse/che-che4z-lsp-for-cobol pull request #1259
Opened 2022-02-10 07:44 UTC by niharikasw91

Signed-off-by: niharikasweta <niharikasw91@gmail.com>

2022-02-10 11:40 UTC, temanbrcom requested changes

2022-02-10 11:40 UTC, temanbrcom commented on server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramNode.java
>      return Optional.empty();
The only difference in logic is the map, so you can just extract a private method and pass the required map there.

2022-02-10 11:40 UTC, temanbrcom commented on server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
> +  private Map<String, List<Location>> extractCopybookUsages(AnalysisResult result) {
The `notifyAnalysisFinished` method uses only a list of copybook URIs, so this logic can be simplified.

2022-02-10 11:40 UTC, temanbrcom commented on server/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/CopybookCompletion.java
> +        .collect(groupingBy(CopyNode::getCopyBookName))
Probably, you don't need to collect it here, just map them to the names.

2022-02-10 11:40 UTC, temanbrcom commented on server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/RootNode.java
> +  public List<SyntaxError> updateCopyNodesByPositionInTree() {
You may keep this method private and call the `process` method in tests instead.

2022-02-10 11:40 UTC, temanbrcom commented on server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseEngine.java
> +        .collect(groupingBy(ParagraphNameNode::getName))
I would recommend adding a `getName` method to the Context object, so you can unify the methods and just specify the node type that you want, and then cast it to the Context type.`getUsages` and `getDefinitions` could be passed as method references.

2022-02-10 17:06 UTC, grianbrcom requested changes
I have nothing significant.

2022-02-16 12:48 UTC, temanbrcom approved these changes
🧱

2022-02-16 13:26 UTC, grianbrcom approved these changes
:four_leaf_clover:

2022-02-16 13:26 UTC, grianbrcom commented on server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
> +        .map(Location::getUri)
Is it make sense to have unique URIs?

2022-02-16 13:26 UTC, grianbrcom commented on server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidNotProcessedInExtendedSource.java
> +            .collect(toList())
You can delete those two lines.

2022-02-16 13:26 UTC, grianbrcom commented on server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
> +        .map(Location::getUri)
I've tested it manually. Seems that it doesn't produce any errors.

2022-02-16 15:05 UTC, grianbrcom approved these changes
:snake:

2022-02-16 16:23 UTC, merged