Provide support for WRK usage of COPY MAID
eclipse/che-che4z-lsp-for-cobol pull request #1283
Opened 2022-03-04 16:02 UTC by temanbrcom

@VitGottwald have fun.
@Nurkambay, @niharikasw91 please, review.

2022-03-04 17:02 UTC, grianbrcom approved these changes
:shark:

2022-03-04 23:31 UTC, niharikasw91 approved these changes

2022-03-14 13:37 UTC, VitGottwald commented
Thank you @temanbrcom ! I tried it out and it looks like the field suffix is appended rather than replacing the suffix from the copybook.

2022-03-15 10:25 UTC, grianbrcom requested changes
All tests are with the previous year.

2022-03-15 10:25 UTC, grianbrcom commented on server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWRK.java
> + * Copyright (c) 2021 Broadcom.
Here is an old year.

2022-03-15 10:43 UTC, zeibura requested changes

2022-03-15 14:16 UTC, zeibura requested changes

2022-03-15 14:16 UTC, zeibura commented on server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkShowsErrorAfter77.java
> +                "Cannot retrieve a suffix for WRK usage",
Cannot retrieve suffix for WRK usage

2022-03-15 14:35 UTC, zeibura approved these changes

2022-03-15 16:40 UTC, temanbrcom commented
@VitGottwald awaiting your conclusion

2022-03-16 09:52 UTC, VitGottwald commented
LGTM @temanbrcom, thank you! 🎉

2022-03-16 10:25 UTC, merged