refactor: Clean COBOL ANTLR grammar
eclipse/che-che4z-lsp-for-cobol pull request #1289
Opened 2022-03-15 13:54 UTC by Nurkambay

2022-03-15 14:37 UTC, grianbrcom requested changes

2022-03-15 14:37 UTC, grianbrcom commented on server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlParser.g4
> +dbs_smallint: T=dbs_integer_constant {validate99($T.text);};//MINUSCHAR? SINGLEDIGITLITERAL SINGLEDIGITLITERAL?;// java ref - -1 to 99
The name is not clear, maybe something `validateTextInRange` and provide the range.

2022-03-16 11:38 UTC, grianbrcom approved these changes
:rice_ball:

2022-03-16 12:16 UTC, Nurkambay commented
> Why didn't you clean up also the IDMS validations in CobolParser?

Good catch. Fixed

2022-03-16 14:11 UTC, merged