doc: Provide changelog for version 1.0.0
eclipse/che-che4z-lsp-for-cobol pull request #1293
Opened 2022-03-21 16:03 UTC by temanbrcom

2022-03-22 10:50 UTC, zimlu02 approved these changes

2022-03-22 23:53 UTC, grianbrcom approved these changes
🌪️

2022-03-22 23:53 UTC, grianbrcom commented on CHANGELOG.md
> +* Enhance the support for obsolete code underscoring ([6749d3d](https://github.com/eclipse/che-che4z-lsp-for-cobol/commit/6749d3d9c601b8baa16f8d00d79c3ddd2b2f41eb))
I think that it was a refactoring.

2022-03-22 23:54 UTC, grianbrcom commented on CHANGELOG.md
> +## [0.22.0](https://github.com/eclipse/che-che4z-lsp-for-cobol/compare/0.21.0...0.22.0) (2022-03-21)
Agree. We need it here.

2022-03-23 09:22 UTC, zimlu02 requested changes

2022-03-23 09:22 UTC, zimlu02 commented on CHANGELOG.md
> +## [0.22.0](https://github.com/eclipse/che-che4z-lsp-for-cobol/compare/0.21.0...0.22.0) (2022-03-21)
good catch Zeb! 
Also the date will change...

2022-03-23 10:06 UTC, temanbrcom commented on CHANGELOG.md
> +* Enhance the support for obsolete code underscoring ([6749d3d](https://github.com/eclipse/che-che4z-lsp-for-cobol/commit/6749d3d9c601b8baa16f8d00d79c3ddd2b2f41eb))
Nice catch

2022-03-23 11:17 UTC, temanbrcom commented on CHANGELOG.md
> +## [0.22.0](https://github.com/eclipse/che-che4z-lsp-for-cobol/compare/0.21.0...0.22.0) (2022-03-21)
Thanks, I updated the version. The date will be updated automatically.

2022-03-23 15:28 UTC, zimlu02 approved these changes

2022-03-24 10:44 UTC, merged