(Doc) Update Readme
eclipse/che-che4z-lsp-for-cobol pull request #1313
Opened 2022-03-30 13:36 UTC by IgorCATech

This PR aims to update Readme by adding 2 sub-sections about the syntax analysis and dialects features.

Signed-off-by: ik673626 <igor.kazmyr@broadcom.com>

2022-03-30 13:58 UTC, grianbrcom approved these changes
:flamingo:

2022-03-31 07:41 UTC, zimlu02 requested changes

2022-03-31 07:41 UTC, zimlu02 commented on README.md
> +### Syntax Analysis
As we've decided to hide this setting from the UI part of settings, I wouldn't mention this option at all in docs. Please check with Aman if his change is part of the release

2022-03-31 11:11 UTC, zimlu02 approved these changes

2022-03-31 11:15 UTC, merged