fix: Allow global FD variable usage inside nested programs.
eclipse/che-che4z-lsp-for-cobol pull request #1363
Opened 2022-05-06 11:47 UTC by ap891843

Signed-off-by: ap891843 <aman.prashant@broadcom.com>

2022-05-06 14:35 UTC, Nurkambay requested changes

2022-05-06 14:35 UTC, Nurkambay commented on server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
> +    boolean isGlobal = !ctx.fileDescriptionEntryClauses().fileDescriptionEntryClause().isEmpty()
Let's move it to separate function

2022-05-06 14:44 UTC, ap891843 commented on server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
> +    boolean isGlobal = !ctx.fileDescriptionEntryClauses().fileDescriptionEntryClause().isEmpty()
Done 👍

2022-05-06 15:20 UTC, Nurkambay approved these changes

2022-05-09 09:43 UTC, ishche approved these changes

2022-05-09 09:59 UTC, merged