New dialect
eclipse/che-che4z-lsp-for-cobol pull request #1440
Opened 2022-06-15 21:25 UTC by niharikasw91

2022-06-21 12:58 UTC, VitGottwald commented on server/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageSnippetsIDMS.json
> +    "prefix": "SCHEMA-SECTION [IDMS]",
Why the [IDMS] tag in prefix?

2022-06-27 14:57 UTC, VitGottwald commented on server/engine/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageSnippetsDaCo.json
> +      "WRITE REPORT ${1:report-name} FROM ${2:layout} TO {3:layout2} LENGTH {4:length}."
Missing $ before {3:layout2} LENGTH {4:length}

2022-06-27 14:58 UTC, VitGottwald commented on server/engine/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageSnippetsDaCo.json
> +      "WRITE REPORT ${1:report-name} FROM ${2:layout} TO {3:layout2} LENGTH {4:length} AFTER {3:id}."
Missing $ before {3:layout2}, {4:length}, and {3:id}

2022-06-27 14:59 UTC, VitGottwald commented on server/engine/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageSnippetsDaCo.json
> +      "WRITE REPORT ${1:report-name} FROM ${2:layout} TO {3:layout2} LENGTH {4:length} AFTER PAGE."
Missing $ signs in front of {3:layout2} and {4:length}

2022-06-27 15:05 UTC, VitGottwald commented
Except for the missing $ signs LGTM.

2022-06-28 12:45 UTC, Nurkambay commented on server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/CompletionStorage.java
> +  protected abstract Map<String, T> getInputStream(List<String> dialectList);
This name does not reflect the meaning of this method. It returns a map, not a stream
Please change it

2022-06-28 12:47 UTC, Nurkambay commented on server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/CompletionStorage.java
> +  private void setDialects(List<Object> dialectObject) {
:thumbsup:

2022-06-28 12:48 UTC, Nurkambay commented on server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/Keywords.java
> +    try {
Let's move it to separate method

2022-06-28 12:50 UTC, Nurkambay commented on server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/Keywords.java
> +        stream =
Let's move all this block to some method that returns a `stream` based on dialectList, for example. It will be easier to read it and test it

2022-06-28 12:51 UTC, Nurkambay commented on server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/Snippets.java
> +    Reader reader = getReader(snippetFileName);
Let's wrap it to try/finally block

2022-06-28 12:52 UTC, Nurkambay commented on server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/Snippets.java
> +  private BufferedReader getReader(String resourceFile) {
Better to name it `createReader`

2022-06-28 12:54 UTC, Nurkambay commented on server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/Snippets.java
> +        } else return idmsSnippets;
Better to have one variable and one `return` statement to understand the logic and to test this method

2022-06-29 08:08 UTC, Nurkambay requested changes

2022-06-29 08:08 UTC, Nurkambay commented on server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/Snippets.java
> +    }
```suggestion
    try (reader = createReader(SNIPPETS_FILE_PATH)) {
      Map<String, SnippetsModel> cobolSnippets = getCobolSnippets(gson, reader);
      if (dialectType.equalsIgnoreCase(DaCoDialect.NAME)) {
        Map<String, SnippetsModel> idmsSnippets = getMergedSnippetsModelMap(SNIPPETS_IDMS_FILE_PATH, cobolSnippets);
        snippetsModelMap = getMergedSnippetsModelMap(SNIPPETS_DACO_FILE_PATH, idmsSnippets);
      } else if (dialectType.equalsIgnoreCase(IdmsDialect.NAME))
        snippetsModelMap = getMergedSnippetsModelMap(SNIPPETS_IDMS_FILE_PATH, cobolSnippets);
      else
        snippetsModelMap = cobolSnippets;
    } catch (IOException e) {
      LOG.error(" Error reading snippets file {}", e.getMessage());
    }
```

2022-06-29 08:15 UTC, Nurkambay approved these changes

2022-06-29 08:24 UTC, niharikasw91 commented on server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/Snippets.java
> +    }
Now I got it,

2022-06-29 08:56 UTC, merged