Idms dml Add support for SCHEMA and MAP sections #704
eclipse/che-che4z-lsp-for-cobol pull request #712
Opened 2021-01-06 12:01 UTC by schte01

2021-01-06 12:27 UTC, temanbrcom requested changes
I would recommend squashing those commits

2021-01-06 12:27 UTC, temanbrcom commented on server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
> +   | SAVE | SCHEMA | SHARED | SHORT_DATE | SQL | SYMBOL
Seems like MAX and VERSION are missing. Is it intentional?

2021-01-06 12:27 UTC, temanbrcom commented on server/src/main/resources/com/broadcom/lsp/cobol/service/delegates/completions/LanguageKeywords.txt
> +SCHEMA=
VERSION is missing

2021-01-06 12:27 UTC, temanbrcom commented on server/src/test/java/com/broadcom/lsp/cobol/usecases/TestIdmsSections.java
> +    private static final String MESSAGE_1 = "rule ss_names_length failed predicate: {_input.LT(1).getText().matches(\"16|18\")}?";
Here and further the lines are not aligned properly

2021-01-06 12:27 UTC, temanbrcom commented on server/src/test/java/com/broadcom/lsp/cobol/usecases/TestIdmsSections.java
> +        UseCaseEngine.runTest(text, List.of(), Map.of("1",
I don't see this id used in the text example

2021-01-06 14:44 UTC, temanbrcom approved these changes
🍪

2021-01-07 11:15 UTC, grianbrcom requested changes
Please, annotate the test. Otherwise, it is not run.

2021-01-07 11:15 UTC, grianbrcom commented on server/src/test/java/com/broadcom/lsp/cobol/usecases/TestIdmsSections.java
> +  void test(String text) {
This looks like a parametrized test. Can you, please, add those annotations:
```
  @ParameterizedTest
  @MethodSource("textsToTest")
```

2021-01-07 11:59 UTC, temanbrcom approved these changes

2021-01-07 12:03 UTC, grianbrcom reviewed
:safety_pin:

2021-01-07 12:12 UTC, grianbrcom approved these changes

2021-01-07 12:26 UTC, merged