feature: Collect and return ranges of paragraphs #777
eclipse/che-che4z-lsp-for-cobol pull request #778
Opened 2021-02-17 10:50 UTC by Nurkambay

2021-02-17 16:07 UTC, grianbrcom requested changes
Please, fix URI related comments.

2021-02-17 16:07 UTC, grianbrcom commented on server/src/main/java/com/broadcom/lsp/cobol/core/model/RangeModel.java
> +public class RangeModel {
The class content confuses me. Looks like it is a range with start and end. But it consists of ranges.
What do you expect as a result of `rangeModel.getStart().getEnd()` or `rangeModel.getEnd().getStart()`?

2021-02-18 16:29 UTC, Nurkambay commented on server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
> +      return new RangeModel(name, start.get().getRange(), end.get().getRange());
Got it, thanks

2021-02-19 11:42 UTC, grianbrcom approved these changes
:leafy_green:

2021-02-19 11:42 UTC, merged