Fix working with URIs provided by E4E #922
eclipse/che-che4z-lsp-for-cobol pull request #927
Opened 2021-05-26 13:52 UTC by temanbrcom

2021-05-27 07:32 UTC, asatklichov approved these changes
Only there is an un-used import in: FileSystemService.java:22:8

2021-05-27 08:27 UTC, grianbrcom requested changes

2021-05-27 08:27 UTC, grianbrcom commented on server/src/main/java/org/eclipse/lsp/cobol/service/utils/WorkspaceFileService.java
> +    return new File(uri).getName().replaceFirst("\\..*$", "");
This will not work with dot-separated dataset names: like `FO2345.COBOL(PROG).CBL`.

2021-05-27 11:48 UTC, grianbrcom approved these changes
:leopard:

2021-05-28 05:53 UTC, nalmabrcom approved these changes

2021-05-28 08:58 UTC, merged